"""pgvector storage driver — owns its own SQLAlchemy engine and Document
table definition, deliberately independent of infrastructure/database/.
ARCHITECTURE.md §4.3: pgvector-specific persistence lives only here, and
infrastructure sub-modules must not import one another directly. The
`documents` table is created by a hand-written Alembic migration, not
autogenerated from infrastructure/database's shared Base/metadata — see the
migration file for why.
"""

from uuid import UUID

from pgvector.sqlalchemy import Vector
from sqlalchemy import Text, create_engine, select
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker

from app.core.config import get_settings
from app.domain.entities.document import Document
from app.domain.entities.search_result import SearchResult
from app.domain.interfaces.vectorstore import IVectorStore
from app.infrastructure.vectorstore.embeddings import EMBEDDING_DIMENSIONS, OllamaEmbedder
from app.infrastructure.vectorstore.retriever import rank_results


class _VectorBase(DeclarativeBase):
    """Scoped to this module only — not shared with infrastructure/database's
    Base (ARCHITECTURE.md §4.3)."""


class DocumentModel(_VectorBase):
    __tablename__ = "documents"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    episode: Mapped[str] = mapped_column(Text, nullable=False)
    speaker: Mapped[str | None] = mapped_column(Text, nullable=True)
    timestamp_range: Mapped[str | None] = mapped_column(Text, nullable=True)
    chunk: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIMENSIONS), nullable=False)


class PgVectorStore(IVectorStore):
    def __init__(
        self,
        embedder: OllamaEmbedder | None = None,
        database_url: str | None = None,
    ) -> None:
        url = database_url or get_settings().database_url
        self._engine = create_engine(url, connect_args={"connect_timeout": 3})
        self._session_factory = sessionmaker(bind=self._engine, expire_on_commit=False)
        self._embedder = embedder or OllamaEmbedder()

    def add_documents(self, documents: list[Document]) -> None:
        with self._session_factory() as session:
            for document in documents:
                embedding = document.embedding or self._embedder.embed(document.chunk)
                session.merge(
                    DocumentModel(
                        id=document.id,
                        title=document.title,
                        source=document.source,
                        episode=document.episode,
                        speaker=document.speaker,
                        timestamp_range=document.timestamp_range,
                        chunk=document.chunk,
                        embedding=embedding,
                    )
                )
            session.commit()

    def search(self, query: str, top_k: int = 5) -> list[SearchResult]:
        query_embedding = self._embedder.embed(query)
        distance = DocumentModel.embedding.cosine_distance(query_embedding)

        with self._session_factory() as session:
            rows = session.execute(
                select(
                    DocumentModel.id,
                    DocumentModel.title,
                    DocumentModel.source,
                    DocumentModel.episode,
                    DocumentModel.speaker,
                    DocumentModel.timestamp_range,
                    DocumentModel.chunk,
                    distance.label("distance"),
                )
                .order_by(distance)
                .limit(top_k)
            ).all()

        return rank_results(rows)
