"""create documents table for pgvector retrieval

Revision ID: 0365a449c420
Revises: f144a33b5570
Create Date: 2026-07-30 21:33:13.223027

Hand-written, not autogenerated: infrastructure/vectorstore/pgvector_store.py
deliberately defines its own SQLAlchemy Base, independent of
infrastructure/database/orm_models.py's Base (ARCHITECTURE.md §4.3 — pgvector
persistence lives only in infrastructure/vectorstore/, and infra sub-modules
must not import one another). `alembic/env.py`'s target_metadata only points
at orm_models.Base, so this table will never show up in `--autogenerate` diffs
and must be evolved by hand going forward.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '0365a449c420'
down_revision: Union[str, Sequence[str], None] = 'f144a33b5570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'documents',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('episode', sa.Text(), nullable=False),
        sa.Column('speaker', sa.Text(), nullable=True),
        sa.Column('timestamp_range', sa.Text(), nullable=True),
        sa.Column('chunk', sa.Text(), nullable=False),
        sa.Column('embedding', Vector(768), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ivfflat requires a non-empty table to train on; skipped for this small,
    # local-first dataset. Revisit if the corpus grows large enough that a
    # sequential scan noticeably slows retrieval.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('documents')
